      - name: Send FCM push
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            -H "Content-Type: application/json; UTF-8" \
            -d '{
              "message": {
                "topic": "zmiany2026",
                "data": {
                  "refresh": "true"
                },
                "notification": {
                  "title": "Zmiany 2026",
                  "body": "Dodano nową informację"
                }
              }
            }' \
            https://fcm.googleapis.com/v1/projects/zmiany2026/messages:send
